### ISSUE TITLE
Can't build, submodules aren't open?

### ISSUE THREAD

**Issue by yesco** [SvenMichaelKlose/tunix#6]
Wanted to check this out for 6502...

But it fails getting submodules, can't even build "Unix"

> git submodule update --init --recursive
Submodule 'src/contrib/cc65' (git@github.com:cc65/cc65.git) registered for path 'src/contrib/cc65'                                          Submodule 'src/contrib/cregex' (git@github.com:jserv/cregex.git) registered for path 'src/contrib/cregex'                                   Submodule 'src/contrib/Unity' (git@github.com:ThrowTheSwitch/Unity.git) registered for path 'src/contrib/unity'                             Cloning into '/data/data/com.termux/files/home/GIT/tunix/src/contrib/cc65'...                                                               git@github.com: Permission denied (publickey).                        fatal: Could not read from remote repository.

**Comment by SvenMichaelKlose** [comment]
Github and my machine prove that the build is OK on Ubuntu/Fedora.

`Cloning into '/data/data/com.termux/files/home/GIT/tunix/src/contrib/cc65'... [git@github.com](mailto:git@github.com): Permission denied (publickey). fatal: Could not read from remote repository.`
Please tell me that you didn't try to build it on an Android phone. :D

**Comment by SvenMichaelKlose** [comment]
The issue seems to be that you're not using SSH with Github. I highly recommend to do so. One big plus about that is that you can clone repositories even if your Internet connection is browning out. With HTTP you have to restart cloning if the Internet gets German.

However: to clone the repos with HTTP, please replace file .gitmodules by this:

`
[submodule "src/contrib/cc65"]
path = src/contrib/cc65
url = https://github.com/cc65/cc65.git

[submodule "src/contrib/cregex"]
path = src/contrib/cregex
url = https://github.com/jserv/cregex.git

[submodule "src/contrib/unity"]
path = src/contrib/unity
url = https://github.com/ThrowTheSwitch/Unity.git
`

Have fun!
